name: 'Pull Request Linker'
description:
  'This action will find all issues linked to the current pull request.'
author: 'Igor Katsuba'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
# inputs:
#   milliseconds:
#     description: 'Your input description here'
#     required: true
#     default: '1000'

# Define your outputs here.
outputs:
  issues:
    description: 'Issues linked to the current pull request'

runs:
  using: node20
  main: dist/index.js
