name: Linker

on:
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Local test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.issues }}"
